### PR TITLE
[ImportVerilog] Able to handle replication, bit/part-select expression, and delete the CAssignOp.

### PR DESCRIPTION
**Pull request by terapines-osc-circt**
The moore::CAssignOp is equivalent to the moore::AssignOp.

### CODE REVIEW

**Comment by fabianschuiki** [comment]
Hi @hailongSun2000, can you try and rebase your changes onto the current `slang-frontend` branch? Thanks! :slightly_smiling_face:

**Comment by terapines-osc-circt** [comment]
> Hi @hailongSun2000, can you try and rebase your changes onto the current `slang-frontend` branch? Thanks! 🙂

Hi @fabianschuiki, I sent an e-mail to you. When I use git rebase -i to squash my commit history, there are many conflicts, and the head is in a state of separation. So may I use git reset 3af865?

I find out you tweak a lot of things. Maybe I should wait to finish adjusting.

**Comment by terapines-osc-circt** [comment]
I express my own opinion, in IEEE 1800-2017 § 11.3 "Operators", Table 11-1 shows the operators and their operand data types. And integral type is different from the simple bit vector type(See IEEE 1800-2017 § 6.11 "Integer data type").

**Comment by fabianschuiki** [comment]
`git reset` sounds like a good idea if the squash destroys the history too much. I'll try to postpone the squashing until we move to upstreaming the `slang-frontend` branch to not interfere with your work -- sorry about that! :cry:

**Comment by terapines-osc-circt** [comment]
Never mind. I will follow your thoughts.:smiley:

**Pull request closed without merging**
