### PR TITLE
[ImportVerilog] Add support for the netType and related test cases.

### PR DESCRIPTION
**Pull request by terapines-osc-circt**
Translating netType(like wire, tri, supply, etc) yields the same Moore MIR form as defining a variable of the logic type.

### CODE REVIEW

**Review by fabianschuiki — APPROVED** [review]
LGTM as a starting point. We'll have to introduce a `moore.net_decl` or similar at a later point and make sure that we capture nets properly. They are quite different from variables, and we'll have to make sure we lower them to the core CIRCT dialects correctly. But this is a great starting point! Thanks a lot! :smile:

**Comment by terapines-osc-circt** [comment]
Sorry, I am using China Standard Time, so I reply to the message now. I noticed that when I declared a variable with wire, I got the same IR as using logic, which is worth noting. Additionally, a similar happens with input and output declarations. I am so glad to get your reply again. I will often seek your advice. I wish you and your family good health and success in your work!

**Comment by fabianschuiki** [comment]
Looking forward to what we can get working here. I'm pretty sure we'll just want to get _something_ working initially, and then flesh out the detailed differences between variables, wires, buffered/unbuffered ports, etc. later. Thanks a lot for contributing!

**Comment by terapines-osc-circt** [comment]
Yeah, I get it. First, I will correctly add support for some functions, and then flesh out the related detail.

**Pull request merged**
